name: cred_lancer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.0
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  eva_icons_flutter: ^3.1.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.16.0
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  date_field: ^3.0.5
  walletconnect_flutter_v2: ^1.2.3
  freezed_annotation: ^2.2.0
  url_launcher: ^6.1.10
  persistent_bottom_nav_bar: ^5.0.2
  web3dart:
    git:
      url: https://github.com/thelazyindian/ow_web3dart.git
      ref: master
  image_picker: ^0.8.7+3
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  hive_generator: ^2.0.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
